ai_folks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import ai_folks.views

urlpatterns = [
    url(r'^$|^index/$', ai_folks.views.index, name='index'),
    url(r'^scholar/', include('scholar.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^admin/', admin.site.urls),
]

scholar/urls.py
from django.conf.urls import url

from . import views
import scholar.views

app_name = 'scholar'
urlpatterns = [
    url(r'^$', scholar.views.field_rank, name='field_rank'),
    url(r'^field/(?P<field>.+)$', scholar.views.field_rank, name='field_rank'),
    url(r'^tag_search/(?P<tag_name>.+)$', scholar.views.tag_search, name='tag_search'),
    url(r'^profile/(?P<scholar_pk>\d+)$', scholar.views.profile, name='profile'),
]

user/urls.py
from django.conf.urls import url
import user.views

app_name = 'user'

urlpatterns = [
    url(r'^login/$', user.views.login, name='login'),
    url(r'^logout/$', user.views.logout, name='logout'),
    url(r'^signup/$', user.views.signup, name='signup'),
    url(r'^account_activation_sent/$', user.views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user.views.activate, name='activate'),
]

scholar/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.

class Scholar(models.Model):
    GENDER_CHOICE = {
        (0, 'Male'),
        (1, 'Female')
    }

    guid = models.CharField(max_length = 50, db_index = True, null = True)
    classification = models.CharField(max_length = 30, blank = True, null = True)
    name = models.CharField(max_length = 100, null = True)
    sex = models.IntegerField(choices = GENDER_CHOICE, null = True)
    birthday = models.DateTimeField(null = True)
    degree = models.CharField(max_length = 1, null = True)
    title = models.CharField(max_length = 1, null = True)
    graduateschool = models.CharField(max_length = 500, null = True)
    subject = models.CharField(max_length = 500, null = True)
    introduction = models.TextField(blank = True, null = True)
    achievement = models.TextField(blank = True, null = True)
    affiliation = models.TextField(blank = True, null = True)
    nationality = models.CharField(max_length = 30, null = True)
    email = models.CharField(max_length = 100, null = True)
    homepage = models.TextField(null = True)
    photourl = models.TextField(null = True)
    lastmodified = models.DateTimeField(null = True)
    keywords = models.TextField(null = True)
    position = models.CharField(max_length = 100, null = True)
    rank = models.IntegerField(null = True)

class Tag(models.Model):
    title = models.CharField(max_length = 20)
    members = models.ManyToManyField(Scholar, through = 'Label')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)
    def __str__(self):
        return self.title

class Label(models.Model):
    scholar = models.ForeignKey(Scholar, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label='username')
    password = forms.CharField(max_length=20, label='password')

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

ai_folks/views.py
from django.shortcuts import render

def index(request):
    return render(request, "ai_index.html")

scholar/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from scholar.models import Scholar

def index(request):
    return HttpResponse("Scholar Index Here")
# Create your views here.


def field_rank(request, field = 'data mining'):
    context = {'scholars': Scholar.objects.filter(classification = field)}
    return render(request, 'scholar/list.html', context)

def tag_search(request, tag_name):
    context = {'scholars': Scholar.objects.filter(tag__title__startswith = tag_name)}
    return render(request, 'scholar/list.html', context)

def profile(request, scholar_pk):
    scholar = get_object_or_404(Scholar, id = scholar_pk)
    return render(request, "scholar/index.html", {
        'scholar': scholar,    
    })

user/views.py
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .forms import LoginForm, SignUpForm
from .tokens import account_activation_token
# Create your views here.

def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('index')

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                django_login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                form.add_error(None, "Invalid username or password")
    
    else:
        form = LoginForm()

    return render(request, 'user/login.html', {'form': form })

def logout(request):
    django_logout(request)
    return render(request, "ai_index.html", {'user': request.user })

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your Account'
            message = render_to_string('user/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            #return redirect('user/account_activation_sent')
            return render(request, 'user/account_activation_sent.html')
        else:
            return HttpResponse(form.errors.as_json())
    else:
        form = SignUpForm()
    return render(request, "user/signup.html", {'form': form})

def account_activation_sent(request):
    return render(request, 'user/account_activation_sent.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        django_login(request, user)
        return render(request, "user/account_activation_success.html")
    else:
        return render(request, "user/account_activation_invalid.html")

scholar/templates/ai_index.html
{% extends "scholar/base.html" %}
{% block content %}
    <div class=' row'>
        <div class='col-xs-12 card'>
            <div class='myTab'>
                <div class='rgzn'>
                <span>人工智能</span>
		     <!--
                     <div class='form'>
                                <form class="form-inline">
                                    <div class="form-group">
                                        <label for="orderKey" style='padding-right: 10px'>排序</label>
                                        <select name="orderKey">
                                            <option>影响力</option>
                                            <option>姓名</option>
                                            <option>领域</option>
                                            <option>标签</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label style='padding-right: 10px'>
                                            <input type="radio" name="order" id="asc" value="asc" checked>
                                            升序
                                        </label>
                                        <label>
                                            <input type="radio" name="order" id="desc" value="desc">
                                            降序
                                        </label>
                                    </div>
                                </form>
                            </div>
                        </div>
                    -->
                        <div class='myTable'>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th width='30%'>人才</th>
                                        <th width='30%'>领域</th>
                                        <th width='40%'>标签</th>
                                    </tr>
                                </thead>
                                {% for person in scholars %}
                                <tbody>
                                    <tr>
                                        <td>
                                            <ul class="media-list">
                                                <li class="media">
                                                    <div class="media-left">
                                                        <a href="#">
                                                            <img class="media-object" src= {{person.photourl}} alt="头像">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        <h4 class="media-heading">
                                                            <a href="{% url 'scholar:profile' person.id %}">{{ person.name }}</a>
                                                        </h4>
                                                        <ul class="introduction">
                                                            <li>{{ person.position}}</li>
                                                        </ul>
                                                    </div>
                                                </li>
                                            </ul>
                                        </td>
                                        <td>
                                            <div style='padding-left: 20px;'>
                                                <ul style='list-style: disc'>
                                                    <li>{{ person.classification }}</li>
                                                </ul>
                                            </div>
                                        </td>
                                        <td>
                                            <span class='tag'>顶级学府</span>
                                            <span class='tag'>顶级学府</span>
                                            <span class='tag'>顶级学府</span>
                                        </td>
                                    </tr>
                                </tbody>
                                {% endfor%}
                            </table>
                        </div>
               </div>
           </div>
	</div>
     </div> 
{% endblock %}

scholar/templates/scholar/index.html
{% extends "scholar/base.html" %}
{% load staticfiles %}
{% block content %}
            <div class=' row'>
                <div class='col-xs-8 card'>
                    <div class="panel panel-default">
                        <div class="panel-heading">{{ scholar.name }}</div>
                        <div class="panel-body" style='height: 300px;overflow:auto;padding: 0 15px;margin: 10px 0;'>
                            <ul class="media-list">
                                <li class="media">
                                    <div class="media-left">
                                        <a href="#">
                                            <img class="media-object" src={{ scholar.photourl }} alt="头像">
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading">
                                            <a href="#">{{ scholar.name }}</a>
                                        </h4>
                                        <ul class="introduction user-info">
                                            <li style='background-image: url("{% static "img/name.jpg" %}")'>{{ scholar.position }}</li>
                                            <li style='background-image: url("{% static "img/addr.png" %}")'>{{ scholar.affiliation }}</li>
                                            <li style='background-image: url("{% static "img/phone.jpg" %}")'></li>
                                            <li style='background-image: url("{% static "img/email.jpg" %}")'>{{ scholar.email }}</li>
                                            <li style='background-image: url("{% static "img/url.jpg" %}")'>{{ scholar.homepage }}</li>
                                            <li style='background-image: url("{% static "img/education.jpg" %}")'>
                                             {{ scholar.graduateschool }}
                                            </li>
                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
		
                <div class='col-xs-4 card'>
                    <div class="panel panel-default">
                        <div class="panel-heading">学术指标</div>
                        <div class="panel-body" style='height: 300px;overflow:auto;padding: 0 15px;margin: 10px 0;'>
                            Coming soon
                        </div>
                    </div>
                </div>

                <div class='col-xs-6 card'>

                    <div class='col-xs-12 card' style="padding: 0 0px 10px;">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                个人标签
                                <span class='save'>添加</span>
                            </div>
                            <div class="panel-body user-tag" style='height: 90px;overflow:auto;padding: 10px 15px 0;margin: 10px 0;'>
			        {% for item in scholar.tag_set.all %}
                                    <span class='col-xs-3 col'><span class='tag'>
					<a href="{%url 'scholar:tag_search' item %}">{{ item }}</a>
				    </span></span>
				{% endfor %}
                            </div>
                        </div>
                    </div>
                    
                    <div class='col-xs-12 card' style="padding: 0 0px 10px;">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                研究兴趣
                                <span class='save'>添加</span>
                            </div>
			    <div class="panel-body user-tag" style='height: 170px;overflow:auto;padding: 10px 15px 0;margin: 10px 0;'>
                                    <div id="main" style="width: 100%;height:100%;"></div>                                    
                            </div>

                        </div>
                    </div>

                </div>

                <div class='col-xs-6 card'>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            学术指标
                            <span class='save'>添加</span>
                        </div>
			<div class="panel-body user-tag" style='height: 330px;overflow:auto;padding: 0 15px 0;margin: 10px 0;'>
			        Coming soon
                                <div id="main2" style="width: 100%;height:100%;"></div>                                    
                        </div>

                    </div>
                </div>
                <!--                
                <div class='col-xs-12 card'>
                    <div class='myTab'>
                        <ul id="myTab" class="nav nav-tabs">
                            <li class="active">
                                <a href="#paper" data-toggle="tab">
                                        paper
                                </a>
                            </li>
                            <li><a href="#report" data-toggle="tab">report</a></li>
                            <li><a href="#patent" data-toggle="tab">patent</a></li>
                        </ul>
                    
                        <div id="myTabContent" class="tab-content">
                            <div class="tab-pane fade in active" id="paper">
                                <table class="table table-striped">
                                    <tbody>
                                        <tr>
                                            <td width='10%'>
                                                <span style='font-size: 24px;'>918</span>
                                            </td>
                                            <td width='40%'>
                                                Mining Reliable Information from Passively and Actively Crowdsourced Data.
                                            </td>
                                            <td width='40%'>
                                                <p style='color: #9fb0ff'>
                                                    Jing Gao, Qi Li, <span style='color:#5574ff'>Bo Zhao</span>, Wei Fan, <span style='color: #ff6367'>Jiawei Han</span>
                                                </p>
                                            </td>
                                            <td width='10%'>
                                                <p style='color: #888991'>KDD(2016)</p>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" id="report">
                                <p>内容</p>
                            </div>
                            <div class="tab-pane fade" id="patent">
                                <p>内容</p>
                            </div>
                        </div>
                    </div>
                </div>
		-->
            </div>
        </div>
        <script>
	  function initEchar(array,key) {
            var myChart = echarts.init(document.getElementById('main'));

            option = {

                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'line',
                        lineStyle: {
                            color: 'rgba(0,0,0,0.2)',
                            width: 1,
                            type: 'solid'
                        }
                    }
                },

                legend: {
                    data: key
                },

                singleAxis: {
                    top: 50,
                    bottom: 50,
                    axisTick: {},
                    axisLabel: {},
                    type: 'time',
                    axisPointer: {
                        animation: true,
                        label: {
                            show: true
                        }
                    },
                    splitLine: {
                        show: true,
                        lineStyle: {
                            type: 'dashed',
                            opacity: 0.2
                        }
                    }
                },

                series: [
                    {
                        type: 'themeRiver',
                        itemStyle: {
                            emphasis: {
                                shadowBlur: 20,
                                shadowColor: 'rgba(0, 0, 0, 0.8)'
                            }
                        },
                        data: array
                    }
                ]
            };
            // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
        }

        function initEchar2() {
            var myChart = echarts.init(document.getElementById('main2'));

            option = {
                tooltip: {},
                legend: {
                    data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）'],
                },
                grid: {
                    top: '20',
                    containLabel: true,
                },
                radar: {
                    // shape: 'circle',
                    name: {
                        textStyle: {
                            color: '#fff',
                            backgroundColor: '#999',
                            borderRadius: 3,
                            padding: [3, 5]
                       }
                    },
                    indicator: [
                       { name: '销售（sales）', max: 6500},
                       { name: '管理（Administration）', max: 16000},
                       { name: '信息技术（Information Techology）', max: 30000},
                       { name: '客服（Customer Support）', max: 38000},
                       { name: '研发（Development）', max: 52000},
                       { name: '市场（Marketing）', max: 25000}
                    ]
                },
                series: [{
                    name: '预算 vs 开销（Budget vs spending）',
                    type: 'radar',
                    // areaStyle: {normal: {}},
                    data : [
                        {
                            value : [4300, 10000, 28000, 35000, 50000, 19000],
                            name : '预算分配（Allocated Budget）'
                        },
                         {
                            value : [5000, 14000, 28000, 31000, 42000, 21000],
                            name : '实际开销（Actual Spending）'
                        }
                    ]
                }]
            };

            // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
        }


	$.ajax({
                url:"https://api.aminer.org/api/person/interests/{{ scholar.guid }}",
                success:function(result){
	            let array = [];
	            let key = [];
	            for (let obj of result.interests) {
	  for (let v of obj.values) {
	  let value = [v[0], v[1], obj.key];
	  array.push(value);
          console.log(value)
	  }
	                key.push(obj.key)
}

                    initEchar(array, key);
                }
        });

	</script>
{% endblock %}

scholar/templates/scholar/list.html
{% extends "scholar/base.html" %}
{% block content %}
    <div class=' row'>
        <div class='col-xs-12 card'>
            <div class='myTab'>
                <div class='rgzn'>
                <span>人工智能</span>
		     <!--
                     <div class='form'>
                                <form class="form-inline">
                                    <div class="form-group">
                                        <label for="orderKey" style='padding-right: 10px'>排序</label>
                                        <select name="orderKey">
                                            <option>影响力</option>
                                            <option>姓名</option>
                                            <option>领域</option>
                                            <option>标签</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label style='padding-right: 10px'>
                                            <input type="radio" name="order" id="asc" value="asc" checked>
                                            升序
                                        </label>
                                        <label>
                                            <input type="radio" name="order" id="desc" value="desc">
                                            降序
                                        </label>
                                    </div>
                                </form>
                            </div>
                        </div>  -->

                        <div class='myTable'>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th width='30%'>人才</th>
                                        <th width='30%'>领域</th>
                                        <th width='40%'>标签</th>
                                    </tr>
                                </thead>
                                {% for person in scholars %}
                                <tbody>
                                    <tr>
                                        <td>
                                            <ul class="media-list">
                                                <li class="media">
                                                    <div class="media-left">
                                                        <a href="#">
                                                            <img class="media-object" src= {{person.photourl}} alt="头像">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        <h4 class="media-heading">
                                                            <a href="{% url 'scholar:profile' person.id %}">{{ person.name }}</a>
                                                        </h4>
                                                        <ul class="introduction">
                                                            <li>{{ person.position}}</li>
                                                        </ul>
                                                    </div>
                                                </li>
                                            </ul>
                                        </td>
                                        <td>
                                            <div style='padding-left: 20px;'>
                                                <ul style='list-style: disc'>
                                                    <li>{{ person.classification }}</li>
                                                </ul>
                                            </div>
                                        </td>
                                        <td>
					    {% for item in person.tag_set.all %}					       
					        {% if item.user_id == request.user.id or item.user == None %}
                                                    <span class='tag'><a href="{% url 'scholar:tag_search' item %}">{{ item }}</a></span>
						{% endif %}
					    {% endfor%}
                                        </td>
                                    </tr>
                                </tbody>
                                {% endfor%}
                            </table>
                        </div>
               </div>
           </div>
	</div>
     </div> 
{% endblock %}

user/templates/user/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

user/templates/user/account_activation_invalid.html
{% extends 'scholar/base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

user/templates/user/account_activation_sent.html
{% extends 'scholar/base.html' %}

{% block content %}
  <p>请在您的邮箱中查找验证邮件，若长时间未收到请在垃圾邮件中寻找.</p>
{% endblock %}

user/templates/user/account_activation_success.html
{% extends 'scholar/base.html' %}

{% block content %}
  <p>邮箱认证成功，您可以正常使用网站了.</p>
{% endblock %}

user/templates/user/login.html
<form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

user/templates/user/signup.html
<h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>